### DISCUSSION TITLE
Composite keybindings + scripting from shell

### DISCUSSION THREAD

**Discussion by s-valent** [ghostty-org/ghostty#2872] [Feature Requests, Ideas]
It would be awesome if ghostty supported more complex keybind actions, maybe such as alacritty's `command = { program ... }`. 

Here is an example of alacritty's shortcut to switch to previous job (I haven't found a way to do it with alacritty's built in keymaps sequences since it requires a delay):
```toml
[[keyboard.bindings]]
key = "["
mods = "Command"
command = { program = "/usr/bin/osascript", args = ['-e', 'tell application "System Events" to keystroke "z" using control down', '-e', 'delay 0.1', '-e', 'tell application "System Events" to keystroke "[" using control down'] }
```

```bash
bind -x '"\C-[": fg %-'
```

With the additional ability to call actions from ghostty cli (for example `ghostty -a write_scrollback_file:paste`, similar to how it is done in tmux) it could enable some potentially interesting scenarios, such as parsing scrollback and opening each file in vim in new tab (or just the file under the cursor).

Potential examples:

```bash
# ~/.config/ghostty/config
keybind = "cmd+[=command:switch_to_previous_job.sh"
keybind = "cmd+o=command:open_file_in_new_tab.sh"
keybind = "cmd+f=command:search.sh"

# switch_to_previous_job.sh
ghostty -a 'text:\x1A'
sleep 0.3
ghostty -a 'text:fg %-\r'

# open_file_in_new_tab.sh
ghostty -a write_scrollback_file | head -n $(ghostty -a get_cursor_position | cut -f 2 -d:) | tail -n1 | xargs ghostty -e vim

# search.sh
file=$(ghostty -a write_scrollback_file)
ghostty -e new_window
ghostty -e resize_window:500,500
ghostty -e toggle_window_decorations
ghostty -e "text:vim $file\r"
```
