### DISCUSSION TITLE
Oh My Posh Right-hand Prompt Character Not Displayed

### DISCUSSION THREAD

**Discussion by cpplain** [ghostty-org/ghostty#3005] [Q&A] [answered]
I searched through discussions and issues but didn't find anything that looked relevant. I use Oh My Posh for my prompt and am seeing a strange issue with the prompt when using Ghostty. The rightmost character in the right hand prompt is missing. Everything is working as expected in my current day-to-day terminal, WezTerm.

In the screenshot below, you can see in the left window (WezTerm) there is a space (" ") used for padding following the execution time. In the right window (Ghostty), the space is not displayed.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/29ee7674-e5e5-4352-a127-c5d64f869428" />

I replaced the space with other characters and had the same result.

Ghostty config:
```
command = /opt/homebrew/bin/fish
font-family = "SF Mono"
font-size = 12
shell-integration = fish
theme = catppuccin-mocha
window-padding-x = 5
window-padding-y = 5
window-padding-balance = true
```

Oh My Posh config:
```toml
"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = false

# Catppuccin Palette

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

#
# Left Block
#

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

# Mode

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "p:base"
template = """\
    <b>\
    {{ if eq \"default\" .Env.OMP_BIND_MODE }}<,p:blue> NORMAL </>{{ end }}\
    {{ if eq \"insert\" .Env.OMP_BIND_MODE }}<,p:green> INSERT </>{{ end }}\
    {{ if eq \"replace\" .Env.OMP_BIND_MODE }}<,p:red> REPLACE </>{{ end }}\
    {{ if eq \"replace_one\" .Env.OMP_BIND_MODE }}<,p:blue> NORMAL </>{{ end }}\
    {{ if eq \"visual\" .Env.OMP_BIND_MODE }}<,p:mauve> VISUAL </>{{ end }}\
    </b>"""

# Git

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = [
  "{{ if eq \"default\" .Env.OMP_BIND_MODE }}p:blue{{ end }}",
  "{{ if eq \"insert\" .Env.OMP_BIND_MODE }}p:green{{ end }}",
  "{{ if eq \"replace\" .Env.OMP_BIND_MODE }}p:red{{ end }}",
  "{{ if eq \"replace_one\" .Env.OMP_BIND_MODE }}p:blue{{ end }}",
  "{{ if eq \"visual\" .Env.OMP_BIND_MODE }}p:mauve{{ end }}",
]
background = "p:surface0"
template = " {{ .Env.OMP_GIT_BRANCH }} "

# Session

[[blocks.segments]]
type = "session"
style = "plain"
foreground = "p:text"
template = " {{ if .SSHSession }}{{ .UserName }}@{{ .HostName }}{{ end }}"

# Path

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "p:text"
background = "p:mantle"
template = " {{ .Path }} "

[blocks.segments.properties]
style = "full"

#
# Right Block
#

[[blocks]]
type = "prompt"
alignment = "right"
filler = "<,p:mantle> </>"

# Shell

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "p:text"
background = "p:mantle"
template = " {{ .Shell }} "

# Execution Time

[[blocks.segments]]
type = "executiontime"
style = "plain"
foreground = "p:base"
background_templates = [
  "{{ if eq \"default\" .Env.OMP_BIND_MODE }}p:blue{{ end }}",
  "{{ if eq \"insert\" .Env.OMP_BIND_MODE }}p:green{{ end }}",
  "{{ if eq \"replace\" .Env.OMP_BIND_MODE }}p:red{{ end }}",
  "{{ if eq \"replace_one\" .Env.OMP_BIND_MODE }}p:blue{{ end }}",
  "{{ if eq \"visual\" .Env.OMP_BIND_MODE }}p:mauve{{ end }}",
]
template = " <b>{{ .FormattedMs }}</b> "

[blocks.segments.properties]
style = "round"
always_enabled = true

#
# Prompt
#

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "status"
style = "plain"
foreground = "p:text"
foreground_templates = ["{{ if gt .Code 0 }}p:red{{ end }}"]
template = "> "

[blocks.segments.properties]
always_enabled = true

[transient_prompt]
foreground = "p:text"
template = "> "
```

WezTerm config:
```lua
local wezterm = require("wezterm")
local mux = wezterm.mux
local config = {}

--
-- Default Config
--

-- In newer versions of wezterm, use the config_builder which will
-- help provide clearer error messages
if wezterm.config_builder then
        config = wezterm.config_builder()
end

--
-- User Config
--

-- Change default shell
config.default_prog = { "/opt/homebrew/bin/fish", "-l" }
if wezterm.target_triple == "x86_64-apple-darwin" then
        config.default_prog = { "/usr/local/bin/fish", "-l" }
end

config.color_scheme = "Catppuccin Mocha"
config.enable_tab_bar = false
config.font = wezterm.font("SF Mono")
config.font_size = 12
-- config.window_decorations = "RESIZE"
-- config.window_padding = {
--      left = 20,
--      right = 20,
--      top = 20,
--      bottom = 20,
-- }

wezterm.on("gui-startup", function(cmd)
        local _, _, window = mux.spawn_window(cmd or {})
        window:gui_window():maximize()
end)

return config
```

Should this be reported as an issue?
