### DISCUSSION TITLE
Black box around right click menu in linux

### DISCUSSION THREAD

**Discussion by anund** [ghostty-org/ghostty#3185] [Feature Requests, Ideas] [answered]
What's missing to get the right click menu to render without this additional black border. 
![blackbox](https://github.com/user-attachments/assets/9cd9676c-d6a7-4ffb-afad-a2ff9faadec4)

**Comment by anund** [comment, marked as answer]
Gtk seems to require additional compositing to for it's default style. A global override will fix this behaviour for gtk 4 apps.

~/.config/gtk-4.0/gtk.css
```css
popover contents {
        border: 1px solid rgb(150,150,150);
        border-radius: 0;
        box-shadow: none;
}
```

![restyled](https://github.com/user-attachments/assets/25504213-3889-40d2-8f49-b49b13de3997)

Relevant gtk issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/4815.
