### DISCUSSION TITLE
Tab bar is nearly transparent with no color

### DISCUSSION THREAD

**Discussion by Leastrio** [ghostty-org/ghostty#3190] [Q&A] [answered]
Hi, I was trying to theme my ghostty with opacity and my tab bar seems to have gone nearly fully transparent. I have a background color set and have tried other settings like setting `window-decoration = true` and `window-theme = ghostty`

Running NixOS with Hyprland

![Image](https://github.com/user-attachments/assets/d0772690-6ba6-4643-a229-95f9f0bdb775)

**Comment by hexchain** [comment]
I've also seen this issue on Plasma 6.2. A minimal configuration example is:

```
background-opacity = 0.99999  # any value less than 1
gtk-titlebar = false
```

The tab bar looks like this when overlaid on top of this page:
![image](https://github.com/user-attachments/assets/fa8ce585-6b7a-4487-90db-21a31971ca0d)

**Reply by Leastrio** [reply]
This seems like a bug to me, as if the tab bar is just not respecting the opacity setting and just going fully transparent

**Comment by Ziqi-Yang** [comment]
Here is my transparent cases (same NixOS with Hyprland):

- use default `window-theme`
- `window-theme = ghostty` and `gtk-titlebar = false`

> I have a background color set and have tried other settings like setting window-decoration = true and window-theme = ghostty

Note when I'm using `window-theme = ghostty` and `window-decoration = false` without setting `gtk-titlebar = false`, the tab bar is not transparent.

**Comment by goproslowyo** [comment, marked as answer]
[Dan over on Discord very helpfully pointed out](https://discord.com/channels/1005603569187160125/1322762820441604166) the `~/.config/gtk-4.0/gtk.css` file and using that I was able to fix the issue I was having with 100% transparent titlebars when also using `window-theme = ghostty` in my Ghostty `~/.config/ghostty/config` configuration.

See if some combination of the information on that thread helps.

This does feel like a bug though since I'd expect the tab-bar styling to follow the theme colors and opacity settings.

EDIT:

#### before
![image](https://github.com/user-attachments/assets/180ab995-faa2-4e66-8021-e7c7ddd7fdb2)


#### after
![image](https://github.com/user-attachments/assets/1cd28c28-f63f-4350-b51b-b2acda389601)

**Comment by ttys3** [comment]
make tabs slim 

![image](https://github.com/user-attachments/assets/fdb12581-0da3-49e1-b3cb-3d84b56ccf16)


~/.config/gtk-4.0/gtk.css

```css
/*
debug: env GTK_DEBUG=interactive ghostty
https://docs.gtk.org/gtk4/css-overview.html
https://docs.gtk.org/gtk4/css-properties.html
*/

headerbar {
  margin: 0;
  padding: 0;
  min-height: 20px;
}

tabbar tabbox {
  margin: 0;
  padding: 0;
  min-height: 10px;
  background-color: #1a1a1a;
  font-family: monospace;
}

tabbar tabbox tab {
  margin: 0;
  padding: 0;
  color: #9ca3af;
  border-right: 1px solid #374151;
}

tabbar tabbox tab:selected {
  background-color: #2d2d2d;
  color: #ffffff;
}

tabbar tabbox tab label {
  font-size: 13px;
}
```

thanks https://discord.com/channels/1005603569187160125/1265734485757136956/1322931497275097138

**Comment by doums** [comment]
Hi, just to let you know this is still an issue (`Ghostty 1.1.3-arch1`) on Linux (X11).
Having to deal with custom GTK CSS style overriding to fix a GUI component is not really what I initially expected for a 0 config philosophy terminal.

Some part of my config
```
window-decoration = false
gtk-titlebar = true
gtk-tabs-location = bottom
adw-toolbar-style = flat
gtk-wide-tabs = false
background-opacity = 0.99999  # any value less than 1
```

**Reply by 00-kat** [reply]
1. None of the maintainers are able to reproduce it.
2. The tab bar is drawn by GTK so it's quite likely this isn't something Ghostty can fix anyway.
3. Nobody has given a concrete reproduction or any way to determine what the actual issue is.

Can't fix it unless you know what to fix ¯\\\_(ツ)\_/¯.

**Reply by doums** [reply]
1), 2) How is it possible? The specific config problematic options have been shared in this discussion thread.

It is pretty straight forward to reproduce it, example
1. On Arch Linux, X11, no particular DE (using https://github.com/yshui/picom as compositor if this is relevant)
2. in an empty config put this

```
background-opacity = 0.99999  # any value less than 1
```

3. launch the terminal and observe the titlebar + tabbar is nearly transparent

Once background-opacity is set to something less than one then that happens.
No matter what I do with the other title bar config option.
The only way I found to fix the bugged background opacity is to use

```
background-opacity = 0.99999
window-theme = ghostty
window-titlebar-background = _somecolor_
```
But then the bar is full opaque (no opacity applied to the bar background).

Please let me know if you need more system info.

**Reply by pluiedev** [reply]
![image](https://github.com/user-attachments/assets/45a39a31-49ce-4348-96b4-73d6b550cf43)

Believe me when I say, we try, we really do. But this really just isn't happening for me. I've tried to replicate your environment as closely as I could: I ran Ghostty using `GDK_BACKEND=x11 ghostty --config-default-files=false --window-decoration=client --background-opacity=0.99999`, to force it to ignore my normal configs, use client-sided decorations, use X11 (which can be seen in the results from `xprop` there), and set the background opacity to what you specified. It just doesn't happen for me, on KWin 6.3, NixOS, GTK 4.16 and so on.

This really either looks like a GTK bug, or a compositor bug. I really don't know what else is wrong here.

**Reply by Kays** [reply]
@doums 

Try doing a bit of what this comment said - https://github.com/ghostty-org/ghostty/discussions/3190?sort=new#discussioncomment-11690311

The only lines you need is this part. You can change the color. Plop that into `~/.config/gtk-4.0/gtk.css`. IDK if it's a configuration thing but you may not have it. If the file or directory doesn't exist, create it. After this, close and reopen ghostty. I agree with pluiedev that this does not appear to be a ghostty-related issue.
```css
tabbar tabbox {
    background-color: #1a1a1a;
}
```

**Reply by 00-kat** [reply]
If the issue doesn't occur in other GTK 4 + libadwaita applications that use tabs, you may also want to consider only overriding it for Ghostty using [`gtk-custom-css`].

[`gtk-custom-css`]: https://ghostty.org/docs/config/reference#gtk-custom-css

**Comment by pmouraguedes** [comment]
Same issue here.
Was using wayland + plasma with no issues.
Installed dwm (X11); as soon as I set up transparency by running `picom`, was able to reproduce this issue.

**Reply by 00-kat** [reply]
…did you try the workarounds mentioned above?  Did you even read them?

**Reply by pmouraguedes** [reply]
Why are you being so blunt?

I'm not complaining, just trying to be helpful and providing additional information, since it was mentioned it was difficult to reproduce...

**Comment by dipakmdhrm** [comment]
I have the same issue. Just cloned the repo and found this in `src/apprt/gtk/class/window.zig`:

```
        // Only add a solid background if we're opaque.
        self.toggleCssClass(
            "background",
            config.@"background-opacity" >= 1,
        );
```

Could this be the cause?

**Comment by shuyiyan123** [comment]
Here is a complete working fix for the GTK titlebar/tabbar going fully transparent when `background-opacity < 1` on GNOME/Wayland. It also fixes the dropdown menu contrast and frame issues that can appear with a light GTK theme.

## 1. Ghostty config

File: `~/.config/ghostty/config.ghostty`

```toml
window-theme = ghostty
window-titlebar-background = #1f1f28
window-titlebar-foreground = #dcd7ba
gtk-custom-css = /home/<user>/.config/ghostty/gtk.css

background-opacity = 0.95
background-blur = true
```

Replace the titlebar colors with your terminal theme background/foreground.

## 2. Ghostty-scoped GTK CSS

File: `~/.config/ghostty/gtk.css`

```css
/* Dark titlebar: visible text and icons */
headerbar,
headerbar label,
headerbar button,
headerbar image,
headerbar windowcontrols button {
  color: #dcd7ba;
}

/* Tab bar */
tabbar,
tabbar tabbox,
tabbar tabbox tab,
tabbar tabbox tab label {
  color: #dcd7ba;
}

tabbar tabbox {
  background-color: #1f1f28;
}

tabbar tabbox tab:selected {
  background-color: #2a2a37;
  color: #ffffff;
}

/* Dropdown menus: keep a light GTK theme readable and remove the frame */
popover > contents,
popover > arrow {
  background-color: #fbf1c7;
  color: #3c3836;
  border: none;
  box-shadow: none;
}

popover.menu modelbutton,
popover.menu label {
  color: #3c3836;
}

popover.menu modelbutton:hover,
popover.menu modelbutton:focus,
popover.menu modelbutton:active {
  background-color: alpha(currentColor, 0.08);
  color: #1d2021;
}
```

## Why these selectors

- `headerbar` is the GTK titlebar. `window-theme = ghostty` plus `window-titlebar-background`/`window-titlebar-foreground` makes it opaque and readable.
- `tabbar tabbox` is Ghostty’s tab bar and needs explicit background/foreground.
- `popover > contents` and `popover > arrow` are the visible popover frame nodes. `popover.background` is not the visible frame, so border/shadow overrides must target `contents` and `arrow`.
- Menu items are `popover.menu modelbutton`, not `button.model`.

The popover block assumes a light GTK theme; for a dark desktop theme, use dark popover colors or omit that block.

Fully quit and reopen Ghostty after applying. `reload_config` may not reload GTK CSS.
