### DISCUSSION TITLE
How do I bind keypresses to tmux sequences?

### DISCUSSION THREAD

**Discussion by joebonneau** [ghostty-org/ghostty#3309] [Q&A] [answered]
I have tmux keybindings that I have mapped to various utility functions, such as `ctrl + b > T` opens up a tmux session picker. I have this mapped to `cmd + k`. In Alacritty, you can map that with the following:

```toml
[[keyboard.bindings]]
chars = "\u0002T"
key = "K"
mods = "Command"
```

or

```yaml
key_bindings:
  - { key: K, mods: Command, chars: "\x02\x54" }
```

I tried this in my Ghostty config with the following, which sends the final keypress (T) instead of triggering ctrl + b, then k:

`keybind = cmd+k=text:\x02\x54`

How do I go about doing this?
