### DISCUSSION TITLE
Create new tab / window via cli

### DISCUSSION THREAD

**Discussion by ricoberger** [ghostty-org/ghostty#3445] [Feature Requests, Ideas] [answered]
It would be great if it is possible to create new tabs / windows via the ghostty cli, e.g. by running `ghostty +new-tab -c <command>` 

Use case: I'm using [gh-dash](https://github.com/dlvhdr/gh-dash), with the following keybindings, to open an issue / pr in a new tmux window and automatically open it in nvim:

```
keybindings:
  issues:
    - key: O
      command: tmux new-window -n "{{.RepoName}}/{{.IssueNumber}}" -c {{.RepoPath}} 'nvim -c ":Octo issue edit {{.IssueNumber}}"'
  prs:
    - key: D
      command: tmux new-window -n "{{.RepoName}}/{{.PrNumber}}" -c {{.RepoPath}} 'gh pr checkout {{.PrNumber}} && nvim -c ":DiffviewOpen main...{{.HeadRefName}}"'
    - key: O
      command: tmux new-window -n "{{.RepoName}}/{{.PrNumber}}" -c {{.RepoPath}} 'nvim -c ":Octo pr edit {{.PrNumber}}"'
```

It would be great if the same can be achieved directly with ghostty, so that tmux is not required for such a use cases.
