### DISCUSSION TITLE
Support for bitmapped fonts (bitfonts)

### DISCUSSION THREAD

**Discussion by keinsell** [ghostty-org/ghostty#3525] [Feature Requests, Ideas] [answered]
I've noticed a difference in bitfont rendering between alacritty and ghostty, as shown in the attached screenshots. The rendering in ghostty resembles that of kitty, which is known for lacking bitfont handling capabilities.

I reviewed the font configuration documentation but did not find any specific mention of bitfont rendering issues or potential enhancements. While this is not a critical issue, it could be beneficial for a niche group of users who prefer using bitfonts. Implementing this feature might improve the experience for those users.

Alacritty: Displays bitfonts distinctively.
Ghostty: Similar to Kitty, does not handle bitfonts adequately.

Will ghostty consider implementing bitfont rendering similar to alacritty or what actions are needed to archive similar result?

### Alacritty

```toml
shell = "nu"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
padding.x = 15
padding.y = 15

[font]
size = 16

[font.normal]
family = "scientifica"

[cursor]
style.blinking = "On"
```

![image](https://github.com/user-attachments/assets/2031cbc7-4938-4b98-8415-b2cd6a38972f)

### Ghostly

```
font-family=scientifica
font-family-bold=scientifica
font-size=16
```

![image](https://github.com/user-attachments/assets/4aaabb1d-3ba5-41a9-a147-593f3e95c0b4)
