### DISCUSSION TITLE
[Bug] ghostty tabs are treated as entire windows by Aerospace and tiled accordingly

### DISCUSSION THREAD

**Discussion by Kareeme246** [ghostty-org/ghostty#3674] [Feature Requests, Ideas] [answered]
I'm wondering if this can be reproduced by anyone else. 
I'm using the latest version of aerospace: 
aerospace CLI client version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8
AeroSpace.app server version: 0.16.2-Beta 21336ad382539b35fdc94b4fbd55408e10b101f8

https://github.com/user-attachments/assets/dc930e5e-4ada-4d0b-93c2-3f808aad03d8

I am using 0 configuration for ghostty.

Aerospace config if needed: 
```toml
after-login-command = []

after-startup-command = [
  # Janky borders: https://github.com/FelixKratz/JankyBorders
  "exec-and-forget borders"
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = "tiles"

default-root-container-orientation = "auto"

key-mapping.preset = "qwerty"

on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]

[gaps]
inner.horizontal = 20
inner.vertical   = 20
outer.top        = 10
outer.right      = 10
outer.bottom     = 10
outer.left       = 10

[mode.main.binding]
alt-slash = "layout tiles horizontal vertical"
alt-comma = "layout accordion horizontal vertical"

alt-shift-f = "fullscreen"
alt-t = "layout floating tiling" # Toggle between floating and tiling layout for a given window
alt-o = "macos-native-fullscreen"

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = "resize smart -30"
alt-shift-equal = "resize smart +30"

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
# alt-tab = "workspace-back-and-forth"
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = "move-workspace-to-monitor --wrap-around next"

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = "mode service"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"] # reset layout
f = ["layout floating tiling", "mode main"] # Toggle between floating and tiling layout
backspace = ["close-all-windows-but-current", "mode main"]

alt-shift-h = ["join-with left", "mode main"]
alt-shift-j = ["join-with down", "mode main"]
alt-shift-k = ["join-with up", "mode main"]
alt-shift-l = ["join-with right", "mode main"]


```
