### DISCUSSION TITLE
[Feature Request] Kitty like tabs style (or more tabs style allow to config)

### DISCUSSION THREAD

**Discussion by ttys3** [ghostty-org/ghostty#3983] [Feature Requests, Ideas] [answered]
I made some custom css, now it looks slim:

```css
/*
debug: env GTK_DEBUG=interactive ghostty
https://docs.gtk.org/gtk4/css-overview.html
https://docs.gtk.org/gtk4/css-properties.html
*/

headerbar {
  margin: 0;
  padding: 0;
  min-height: 20px;
}

tabbar tabbox {
  margin: 0;
  padding: 0;
  min-height: 10px;
  background-color: #1a1a1a;
  font-family: monospace;
}

tabbar tabbox tab {
  margin: 0;
  padding: 0;
  color: #9ca3af;
  border-right: 1px solid #374151;
}

tabbar tabbox tab:selected {
  background-color: #2d2d2d;
  color: #ffffff;
}

tabbar tabbox tab label {
  font-size: 13px;
}
```

![image](https://github.com/user-attachments/assets/432f1807-f1df-48aa-b5f6-dd71d3056c81)

in order to style the tabs, we may need to use custom tab, instead of using GTK default ?

-----------------

related issue: https://github.com/ghostty-org/ghostty/discussions/3297
