### DISCUSSION TITLE
Cherry-picked Iosevka ligatures work in other terminals, but not Ghostty

### DISCUSSION THREAD

**Discussion by ferdinandrau** [ghostty-org/ghostty#4592] [Feature Requests, Ideas] [answered]
The popular [Iosevka](https://github.com/be5invis/Iosevka) font allows users to create a [custom build](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md) to fine-tune the appearance. I used this to selectively enable only some of the ligatures it offers, as I only want "non intrusive" ligations (like connected arrows `-->`) and not those that obscure the individual characters (like the connected `!=` that turns into a strikethrough-equals `≠`). My custom build works fine in Kitty and iTerm, but running **Ghostty**, all ligatures the font offers show up, even the ones I disabled:

<img width="247" alt="grafik" src="https://github.com/user-attachments/assets/4b45c204-5dab-4ae2-9f13-573242f5ec85" />

The image has Ghostty on the left and iTerm, behaving as expected, on the right.

I am aware that this _may_ not be a Ghossty issue, since this project is pretty good with standards, and perhaps Iosevka is not following one of them. But the other terminals handle the custom-built font just fine and display what is expected. I sadly don't know much about fonts and thus can't really judge where to report this issue.

**Ghostty version (running on macOS 15.2):**

```
Ghostty 1.0.1

Version
  - version: 1.0.1
  - channel: stable
Build Config
  - Zig version: 0.13.0
  - build mode : builtin.OptimizeMode.ReleaseFast
  - app runtime: apprt.Runtime.none
  - font engine: font.main.Backend.coretext
  - renderer   : renderer.Metal
  - libxev     : main.Backend.kqueue
```

**How to reproduce:**

1. This is the `private-build-plans.toml` used to build the font:
    ```toml
    [buildPlans.Ioveska]
    family = "Ioveska"
    serifs = "sans"
    spacing = "term"
    exportGlyphNames = true
    noCvSs = true
    
    [buildPlans.Ioveska.widths.Normal]
    shape = 560
    menu = 5
    css = "normal"
    
    [buildPlans.Ioveska.weights.Regular]
    shape = 450
    menu = 400
    css = 400
    
    [buildPlans.Ioveska.weights.Bold]
    shape = 750
    menu = 700
    css = 700
    
    [buildPlans.Ioveska.variants.design]
    asterisk = "penta-low"
    percent = "rings-continuous-slash"
    lig-single-arrow-bar = "with-notch"
    lig-double-arrow-bar = "with-notch"
    
    [buildPlans.Ioveska.ligations]
    enables = [
      "arrow-l",
      "arrow-r",
      "arrow-lr",
      "lteq-separate",
      "gteq-separate",
      "kern-dotty",
      "kern-bars",
    ]
    ```
   I could probably distribute the finished files (it's 4 `.ttf`s) under the license if desired. https://fontdrop.info shows that all ligatures, even the disabled ones, are still _present_ in the file (duh).

2. Install the font and set it as the default:
   ```ini
   # ~/.config/ghostty/config

   font-family = Ioveska
   font-size = 15
   ```
   For comparison, also configure another Terminal like iTerm to use "Ioveska".

3. Enter something like `>=`. In Ghostty, it becomes a connected symbol, whereas iTerm and Kitty show the individual characters.
