### DISCUSSION TITLE
Standard unicode star breaks font rendering

### DISCUSSION THREAD

**Discussion by fabolous005** [ghostty-org/ghostty#4767] [Feature Requests, Ideas] [answered]
This one is oddly specific, but always reproducible...

I discovered this when opening the profile tab of [lazy.nvim](https://github.com/folke/lazy.nvim), i would always get this screen:
![image](https://github.com/user-attachments/assets/ff83d474-7e9a-46f2-b53c-459b59dac44d)

This was very strange to me and after some testing i discovered that narrowing the size of the window the screen would go normal again...

After some more digging i found the root of issue, it's this:
[Found here](https://github.com/folke/lazy.nvim/blob/main/lua/lazy/core/config.lua#L118)
`<★> 9733, Hex 2605, Oct 23005, Digr *2` (Obtained using neovim [`ga`](https://neovim.io/doc/user/various.html#ga))

Whenever this character shows up every cell *upwards* will be blank.

<details>
<summary>Debug stuff</summary>

```yaml
Ghostty 1.0.2-HEAD+a3837a1e

Version
  - version: 1.0.2-HEAD+a3837a1e
  - channel: tip
Build Config
  - Zig version: 0.13.0
  - build mode : builtin.OptimizeMode.ReleaseFast
  - app runtime: apprt.Runtime.glfw
  - font engine: font.main.Backend.fontconfig_freetype
  - renderer   : renderer.OpenGL
  - libxev     : main.Backend.io_uring
 ```

`fontconfig version 2.15.0`

Btw Kitty works fine (compiled with same library and version)
Let me know if u need anything else...

</details>
