### DISCUSSION TITLE
Aerospace workspace change issues when focusing Ghostty

### DISCUSSION THREAD

**Discussion by gabimoncha** [ghostty-org/ghostty#5606] [Q&A] [answered]
I'm using Aerospace for window management with the following config

```toml
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
# etc...
```

But everytime i focus on Ghostty's workspace, the terminal autofocuses and inserts the keyboard's input special characters
Even if a disable the option key from keyboard modifiers doesn't fix it. Is there a way to disable this feature/bug?
