### DISCUSSION TITLE
Image preview in Yazi has pixels cut off

### DISCUSSION THREAD

**Discussion by hankertrix** [ghostty-org/ghostty#5805] [Issue Triage] [answered]
Here is an image being previewed in Ghostty:

![image](https://github.com/user-attachments/assets/2c0f0ec9-a924-4f81-a867-0b22d49962b2)

Here is the same image being previewed in Kitty:

![image](https://github.com/user-attachments/assets/c01a6b0b-11d4-47a3-a2d1-ab4774ef96e6)

The image being previewed in Ghostty has some pixels on the right being cut off.

The original image is below:

![cyberpunk-mclaren-supercars-neon-art-3840x2160-1003](https://github.com/user-attachments/assets/9e5cd929-b0ea-45b8-a673-1997657273e6)

Here is my Yazi configuration for the previewer:

```toml
# Configuration for the file previewer
[preview]

# Wrap long lines for text previews
wrap = "yes"

# Make the maximum size of the images larger
max_width = 3000
max_height = 3000
```
