### DISCUSSION TITLE
Vim: missing italics

### DISCUSSION THREAD

**Discussion by dimaqq** [ghostty-org/ghostty#5852] [Issue Triage] [answered]
![Screenshot 2025-02-18 at 14 44 35](https://github.com/user-attachments/assets/0b9ea32f-5f23-4c7c-b86e-a6223908c930)

Somehow ViM refuses to send italics. Or sends the wrong sequence.

I do get italics with a manual test `echo -e "Regular text \033[3mItalic text\033[0m"`.

My config:

```toml
background = "#000"
font-family = "Monaco"

cursor-style-blink = false

font-family = "Monaco"
font-size = 14
font-thicken = true
adjust-cell-width = -7%

# term = xterm-ghostty
term = xterm-256color
```

Same issue with default and adjusted TERM.
Looking at environment, one possible source of difference is that Ghosttty sets:
```
COLORTERM=truecolor
TERMINFO=/Applications/Ghostty.app/Contents/Resources/terminfo
TERM_PROGRAM=ghostty
TERM_PROGRAM_VERSION=1.1.2
TERM=xterm-256color
```
While iTerm2 sets:
```
TERMINFO_DIRS=/Applications/iTerm.app/Contents/Resources/terminfo:/usr/share/terminfo
COLORTERM=truecolor
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.5.11
LC_TERMINAL_VERSION=3.5.11
ITERM_PROFILE=Default
TERM_FEATURES=T3LrMSc7UUw9Ts3BFGsSyHNoSxF
TERM=xterm-256color
LC_TERMINAL=iTerm2
```
