### DISCUSSION TITLE
Reduce Height of Title and Tab-Bars

### DISCUSSION THREAD

**Discussion by andyl** [ghostty-org/ghostty#5882] [Q&A] [answered]
I cannot find the CSS settings to reduce the height of my tabbar and titlebar.  Any pointers appreciated!  Using Xubuntu 22.04.

![image](https://github.com/user-attachments/assets/47017476-dc1b-4eb4-be4a-c02e2a4967c2)

```css
/*
debug: GTK_DEBUG=interactive ghostty
https://docs.gtk.org/gtk4/css-overview.html
https://docs.gtk.org/gtk4/css-properties.html
*/

headerbar {
  height: 10px;
  padding: 0;
  margin: 0;
  background-color: #8aaaaa; 
}

headerbar button { 
  background-color: #aaaa88; 
  margin: 0;
  border: 1px solid black;
}

headerbar button image { 
  background-color: orange; 
  padding: 0; 
  margin: 0;
}

tabbox {
  font-family: monospace;
  margin: 0;
  padding: 0;
}

tabbox tab {
  margin: 0;
  padding: 0;
  color: #00000f;
  background-color: #99aaaa;
  border-right: 1px solid #374151;
}

tabbox tab label { 
  font-size: 12px;
  border: 1px solid blue;
  margin: 0;
  padding: 0;
}

tabbox tab:checked  { background-color: #98ee98; }

tabbox tab:default  { background-color: #ac2d0d; }
tabbox tab:target   { background-color: #ac6d2d; }
tabbox tab:disabled { background-color: #ac0d7d; }
tabbox tab:enabled  { background-color: #0c2ded; }
tabbox tab:hover    { background-color: #ac2ded; }
tabbox tab:focus    { background-color: #aced0d; }
tabbox tab:active   { background-color: #2caded; }
tabbox tab:selected { background-color: #ac2d2d; }
```

**Comment by okraits** [comment]
See this: https://github.com/ghostty-org/ghostty/discussions/3297#discussioncomment-11861813

**Reply by andyl** [reply]
I studied that example closely.  Some of the settings worked, but could not adjust the height of the tabbar or titlebar.

**Comment by 00-kat** [comment]
> height: 10px;

Run Ghostty from the CLI to get CSS errors:
> ```
> (process:18047): Gtk-WARNING **: 10:08:17.727: Theme parser error: <data>:10:5-11: No property named "height"
> ```

You want `min-height`; it's not possible to set the actual position or size of elements from GTK CSS.

Also: based on my experimentation, I don't think it's possible to make the **headerbar** smaller than around 24 pixels; I was able to make the **tab bar** super small though.  Try it anyway, in case it works for you.

**Reply by andyl** [reply]
Thanks for this tip.  Helpful.

**Comment by andyl** [comment]
The answer is: it doesn't seem to work.

**Comment by eioo** [comment]
I had luck by using negative margin for the `headerbar` selector, guess the same would work the tab bars too.

```css
headerbar {
  margin: -8px;
}
```

![image](https://github.com/user-attachments/assets/c5f4f56e-b0ca-460d-b623-bfd5662f5a71)

**Reply by eioo** [reply, marked as answer]
This works for the tab bar, combination of negative margin and then CSS transform to align the text properly.

```css
tabbar {
  margin: -16px;
}

tabbar tabbox {
  transform: translateY(-8px);
}
```

<details><summary>Full CSS to get styles like in the image</summary>
<p>

```css
headerbar {
  margin: -8px;
  margin-left: -6px;
  margin-right: -6px;
}

headerbar button {
  min-height: 8px;
  min-width: 8px;
}

tabbar {
  margin-top: -16px;
  margin-bottom: -16px;
}

tabbar tabbox {
  transform: translateY(-8px);
  background-color: #1a1a1a;
  font-family: monospace;
}

tabbar tabbox button {
  min-height: 20px;
  min-width: 20px;
}
```

</p>
</details> 

![image](https://github.com/user-attachments/assets/4d32969c-00aa-4608-a8d8-79f4f375d32a)
