### DISCUSSION TITLE
GTK: Can't reduce height of titlebar or tabbar

### DISCUSSION THREAD

**Discussion by andyl** [ghostty-org/ghostty#5914] [Issue Triage] [answered]
I'm using Xubuntu 22.04.  Using CSS, I can't make the titlebar / tabbar thinner than ~24px.   Note: using `headerbar { min-height: 100px }` works to INCREASE the height.  Maybe one of the nested elements causes the problem.  This might be a rendering bug, or maybe it could be solved with documentation and examples. 

Here's a screenshot: 
![image](https://github.com/user-attachments/assets/e30085b3-26c4-40ef-83cd-8f6eb8fae3d8)

Here's my CSS: 
```css
/*
debug: GTK_DEBUG=interactive ghostty
https://docs.gtk.org/gtk4/css-overview.html
https://docs.gtk.org/gtk4/css-properties.html
*/

headerbar {
  min-height: 10px;
  margin: 0;
  padding: 0;
  background-color: #80a0a0; 
}

headerbar button { 
  margin: 0;
  min-height: 10px; 

  background-color: #aaaa88; 
  border: 1px solid black;
}

headerbar button image { 
  margin: 0;
  padding: 0; 

  background-color: orange; 
}

tabbar tabbox {
  margin: 0;
  padding: 0;
  min-height: 10px;
  font-family: monospace;
}

tabbox tab {
  color: #00000f;
  margin: 0;
  padding: 0;
  min-height: 10px;
  background-color: #99aaaa;
  border-right: 1px solid #374151;
}

tabbox tab label { 
  margin: 0;
  padding: 0;
  font-size: 12px;
  min-height: 10px; 

  border: 1px solid blue;
}

tabbox tab:checked  { background-color: #98ab08; }
tabbox tab:hover    { background-color: #889999; }

```
