### DISCUSSION TITLE
GTK CSS: Class name for active tab in tab bar

### DISCUSSION THREAD

**Discussion by acarl005** [ghostty-org/ghostty#7598] [Feature Requests, Ideas] [answered]
Hello. I really love the ability to load custom CSS for GTK.

What I would like is the ability to choose the styling for the **active** tab. For example, something like this:

```css
.top-bar tab.active {
    background: #a1a1a1;
}
```

However, there is no class to differentiate the active tab. They have to have the same exact background currently.
