### ISSUE TITLE
Lag on focusing instances with mouse and selecting text with mouse

### ISSUE THREAD

**Issue by Syphdias** [ghostty-org/ghostty#2210]
Sadly, I have no concrete steps to reproduce this. It just happens after a while.
In https://ptb.discord.com/channels/1005603569187160125/1280945530540920985/1282802984362967115 I tried to gather more information and observations.

Observations:
- The entire machine is fine and not slow: Browser and other terminals are not affected
- If I open another terminal and start `ghostty -e zsh` (separate instance), it behaves completely normal
- Only terminals that are part/attach to the gtk-single-instace are affected (also newly opened ones)
- just running commands and generally working in the terminal is **not** slow
- If I focus from another window to a ghostty instance with keyboard shortcuts everything works fine (no delay)
- If I focus with the mouse to a ghostty instance: it takes a while untill the hollow block cursor gets converted to blinking bar and I can start to type
- if I type while the cursor is stuck the text will show up, just delayed, even if the window is no longer focused
- the cursor stops blinking if I move the mouse
- selecting text with the mouse has a delay until the selection gets highlighted
- resizing with mouse has a delay
- resizing with keyboard shortcuts has a delay (smaller than with mouse; but still slower than separate `-e` ghostty instance) 
- the longer I wait or the more I focus with my mouse, the worse it gets
- While doing this `btop` shows 100% CPU usage for `ghostty`

[Peek 2024-09-09 23-16.webm](https://github.com/user-attachments/assets/8f8c9ed5-7fe1-4a81-8b4e-3baefb8118d4)

[Peek 2024-09-09 23-17.webm](https://github.com/user-attachments/assets/768ea024-f6be-46e7-a1d2-ec3a3c446907)

Part of a strace while it was slow:
```strace
❯ sudo strace -p $(pidof ghostty) -ff -s999 -tt
Tap the Yubikey to Sudo
strace: Process 106611 attached with 12 threads
[pid 280339] 23:15:33.008813 restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 280337] 23:15:33.008846 io_uring_enter(73, 0, 1, IORING_ENTER_GETEVENTS, NULL, 8 <unfinished ...>
[pid 280336] 23:15:33.008864 io_uring_enter(54, 0, 1, IORING_ENTER_GETEVENTS, NULL, 8 <unfinished ...>
[pid 106625] 23:15:33.008874 restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 106623] 23:15:33.008882 io_uring_enter(36, 0, 1, IORING_ENTER_GETEVENTS, NULL, 8 <unfinished ...>
[pid 106622] 23:15:33.008891 io_uring_enter(32, 0, 1, IORING_ENTER_GETEVENTS, NULL, 8 <unfinished ...>
[pid 106618] 23:15:33.008907 futex(0x40472920, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid 106617] 23:15:33.008924 restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 106616] 23:15:33.008932 restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 106614] 23:15:33.008941 restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 106613] 23:15:33.008969 futex(0x40435e50, FUTEX_WAIT_PRIVATE, 21, NULL <unfinished ...>
[pid 280336] 23:15:33.500727 <... io_uring_enter resumed>) = 0
[pid 280336] 23:15:33.500773 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:33.500871 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:33.500929 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:33.500990 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:33.501265 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:33.501330 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:33.501376 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:34.100941 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:34.101026 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:34.101083 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:34.101145 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:34.101366 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:34.101476 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:34.101583 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:34.701091 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:34.701168 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:34.701214 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:34.701265 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:34.701446 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:34.701500 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:34.701538 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:35.301236 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:35.301333 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:35.301395 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:35.301453 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:35.301649 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:35.301721 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:35.301776 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:35.901383 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:35.901446 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:35.901490 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:35.901568 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:35.901858 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:35.901933 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:35.901983 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:36.501504 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:36.501568 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:36.501603 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:36.501638 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:36.501816 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:36.501877 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:36.501912 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:37.101652 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:37.101753 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:37.101848 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:37.101914 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:37.102262 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:37.102410 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:37.102577 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:37.701818 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:37.701900 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:37.701952 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:37.702009 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:37.702228 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:37.702287 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:37.702344 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:38.301960 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:38.302036 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:38.302078 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:38.302136 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:38.302371 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:38.302449 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:38.302514 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:38.902105 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:38.902173 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:38.902232 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:38.902278 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:38.902479 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:38.902527 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:38.902554 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:39.502277 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:39.502368 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:39.502438 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:39.502577 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:39.502810 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:39.502905 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:39.502945 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:40.102443 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:40.102558 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:40.102623 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:40.102708 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:40.102952 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:40.103036 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:40.103088 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:40.702638 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:40.702735 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:40.702822 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:40.702886 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:40.703131 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:40.703208 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:40.703293 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:41.302796 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:41.302881 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:41.302940 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:41.302992 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:41.303175 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:41.303242 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:41.303294 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:41.902976 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:41.903080 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:41.903143 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:41.903205 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:41.903498 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:41.903608 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:41.903702 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:42.503148 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:42.503268 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:42.503358 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:42.503444 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:42.503726 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:42.503877 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:42.503996 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:43.103349 write(70, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:43.103455 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8) = 1
[pid 280336] 23:15:43.103510 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:43.103568 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:43.103758 munmap(0x7bfcd0f27000, 888832) = 0
[pid 280336] 23:15:43.103865 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 280336] 23:15:43.103908 io_uring_enter(54, 1, 1, IORING_ENTER_GETEVENTS, NULL, 8 <unfinished ...>
[pid 106611] 23:15:43.272855 poll([{fd=10, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLIN|POLLOUT}])
```

It looks like the same memory is mapped and unmapped immediately after (over and over again):
```strace
[pid 280336] 23:15:39.502577 mmap(0x7bfcd1000000, 888832, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bfcd0f27000
[pid 280336] 23:15:39.502810 munmap(0x7bfcd0f27000, 888832) = 0
Send a message in "Bad performance on Linux after a while"
```
Also the writes might be related to my graphics card:
```strace
[pid 280336] 23:15:38.302449 write(7, "\1\0\0\0\0\0\0\0", 8) = 8
```
```
❯ ls /proc/$(pidof ghostty)/fd/{7,8} -l
lrwx------ 1 syphdias syphdias 64 Sep  9 22:49 /proc/106611/fd/7 -> 'anon_inode:[eventfd]'
lrwx------ 1 syphdias syphdias 64 Sep  9 22:49 /proc/106611/fd/8 -> /dev/nvidiactl
```

**Comment by riddley** [comment]
Hello. I'm using the AppImage on Debian 12 with an AMD graphics card (two machines, actually) and I'm seeing this all the time. I haven't seen this mentioned so hopefully it's helpful to add that long-lived (5+days) ghostty windows that have done a lot of text selection with the mouse will sometimes take 30s or more to draw when switching virtual desktops in the Mate desktop environment in X11. Sometimes the select lag/general slowdown happens very quickly and as mentioned it sometimes takes several days. Switching back to a desktop that has Ghostty windows will result in those windows just not appearing on the screen and then some time later they draw. During this I'm not seeing obvious jumps in CPU or RAM usage, but I'm also not measuring it in a scientific way.

Hope this helps.

**Comment by h3** [comment]
I don't know if that information can help, but I initially had 4 displays (2x 1440p, 2x 1080p) and ghostty was fast.

I found out that my main GPU worked fine with my on board graphic card, so I upgraded my setup. I now have 5x 1440p monitors and 2x 1080p.

Since I upgraded my setup ghostty is _very_ slow, almost unusable. When I click on a tab or within the terminal to select text, it takes a solid 2~3 seconds for the window to start responding. 

If I get to the ghostty window using alt+tab, then I have zero lag and can start typing, but then using the mouse to select text will still have a quite a bit of lag.

```
Graphics:
  Device-1: Intel Raptor Lake-S GT1 [UHD Graphics 770] vendor: Lenovo
    driver: i915 v: kernel alternate: xe arch: Gen-13 process: Intel 7 (10nm)
    built: 2022+ ports: active: DP-1,DP-3,HDMI-A-1 empty: DP-2, HDMI-A-2,
    HDMI-A-3, HDMI-A-4 bus-ID: 00:02.0 chip-ID: 8086:a780 class-ID: 0380
  Device-2: NVIDIA GA106 [RTX A2000 12GB] vendor: Lenovo driver: nvidia
    v: 550.120 alternate: nvidiafb,nouveau,nvidia_drm non-free: 550.xx+
    status: current (as of 2024-04; EOL~2026-12-xx) arch: Ampere code: GAxxx
    process: TSMC n7 (7nm) built: 2020-2023 pcie: gen: 4 speed: 16 GT/s
    lanes: 16 ports: active: none off: DP-4, DP-5, DP-6, DP-7 empty: none
    bus-ID: 01:00.0 chip-ID: 10de:2571 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6
    compositor: gnome-shell v: 46.0 driver: X: loaded: modesetting,nouveau
    unloaded: fbdev,vesa failed: nvidia dri: iris
    gpu: i915,nvidia,nvidia-nvswitch display-ID: :1 screens: 1
  Screen-1: 0 s-res: 9600x2880 s-dpi: 96 s-size: 2540x762mm (100.00x30.00")
    s-diag: 2652mm (104.4")
  Monitor-1: DP-0 pos: primary,3-4 res: 2560x1440 hz: 60 dpi: 109
    size: 597x336mm (23.5x13.23") diag: 685mm (26.97") modes: N/A
  Monitor-2: DP-2-1 pos: 3-1 res: 2560x1440 hz: 60 dpi: 109
    size: 597x336mm (23.5x13.23") diag: 685mm (26.97") modes: N/A
  Monitor-3: DP-2-3 pos: 2-2 res: 1920x1080 hz: 60 dpi: 93
    size: 527x296mm (20.75x11.65") diag: 604mm (23.8") modes: N/A
  Monitor-4: DP-3 pos: 1-4 res: 2560x1440 hz: 60 dpi: 109
    size: 597x336mm (23.5x13.23") diag: 685mm (26.97") modes: N/A
  Monitor-5: DP-4 pos: 3-3 res: 2560x1440 hz: 60 dpi: 109
    size: 597x336mm (23.5x13.23") diag: 685mm (26.97") modes: N/A
  Monitor-6: DP-6 pos: 1-3 res: 2560x1440 hz: 60 dpi: 109
    size: 597x336mm (23.5x13.23") diag: 685mm (26.97") modes: N/A
  Monitor-7: HDMI-2-1 pos: 3-5 res: 1920x1080 hz: 60 dpi: 93
    size: 527x296mm (20.75x11.65") diag: 604mm (23.8") modes: N/A
  API: EGL v: 1.5 hw: drv: intel iris drv: nvidia platforms: device: 0
    drv: nvidia device: 1 drv: iris device: 3 drv: swrast gbm: drv: iris
    surfaceless: drv: nvidia x11: drv: nvidia inactive: wayland,device-2
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.120
    glx-v: 1.4 direct-render: yes renderer: NVIDIA RTX A2000 12GB/PCIe/SSE2
    memory: 11.71 GiB
```
